version: '2.2'
services:
  config:
    build: ./config/
    healthcheck:
        test: curl -f http://localhost:8888/proxy/default && echo 'cool, it works'
        interval: 10s
        timeout: 10s
        retries: 5
    networks:
     - back
    ports:
     - "8888:8888"
  annuaire:
    build: ./annuaire/
    networks:
     - back
    ports:
     - "1111:1111"
    depends_on: 
      config:
        condition: service_healthy
  document-service:
    build: ./document-service/
    networks:
     - back
    depends_on: 
      config:
        condition: service_healthy
  notification-service:
    build: ./notification-service/
    networks:
     - back
    depends_on: 
      config:
        condition: service_healthy
  members-service:
    build: ./members-service/
    networks:
      - back
    depends_on: 
      config:
        condition: service_healthy
  turbine:
    build: ./turbine/
    networks:
      - back
    depends_on: 
      config:
        condition: service_healthy
    ports:
     - "5555:5555"
  proxy:
    build: ./proxy/
    networks:
      - front
      - back
    ports:
      - 8081:8081
    depends_on: 
      config:
        condition: service_healthy
  fake-smtp:
    build: ./fake-smtp/
    networks:
      - front


networks:
  back:
  front:
