spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
      bindings:
        positions-out:
          destination: position
          contentType: application/json          
      
