apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: members-service
build:
  artifacts:
  - image: dthibau/members-service
    context: .
    jib: 
      args:
      - -DskipTests
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
