

feign:
  hystrix:
    enabled: true

spring:
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1
            
management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - metrics
        - httptrace
        - refresh
        - mappings
        - hystrix.stream
        - routes
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO   
    com.netflix.discovery: ERROR
    
--- 
spring:
  profiles: netflix
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://annuaire:1111/eureka/,http://annuaire:1112/eureka/
    healthcheck:
      enabled: true
    LeaseRenewalIntervalInSeconds: 5
