apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-${BRANCH_NAME}
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  POSTGRES_SERVICE: postgres-service-$BRANCH_NAME