
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-smtp
  template:
    metadata:
      labels:
        app: fake-smtp
    spec:
      containers:
        - name: fake-smtp
          image: dthibau/fake-smtp:1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 2525

---

apiVersion: v1
kind: Service
metadata:
  name: fake-smtp
  labels:
    app: fake-smtp
spec:
  type: ClusterIP
  ports:
   - port: 2525
  selector:
   app: fake-smtp           
