---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NOTIFICATION_USERNAME
          valueFrom:
              secretKeyRef:
                name: smtp-secret
                key: username
        - name: NOTIFICATION_PASSWORD
          valueFrom:
              secretKeyRef:
                name: smtp-secret
                key: password
        image: dthibau/notification-service:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        volumeMounts:
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
      volumes:
        - name: secrets
          secret:
            secretName: smtp-secret


---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
  - name: http-notification
    port: 9090
  selector:
    app: notification-service  