---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.io/git-branch: sck
    jkube.io/git-url: git@github.com:dthibau/springcloudsolutions.git
    jkube.io/git-commit: 9b17ea490debaddb6078683a5b11f18e0447cc3b
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/delivery-service
    jkube.io/scm-tag: HEAD
  labels:
    app: delivery-service
    provider: jkube
    version: 0.0.8-SNAPSHOT
    group: org.dthibau
  name: delivery-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: delivery-service
      provider: jkube
      group: org.dthibau
  template:
    metadata:
      annotations:
        jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/delivery-service
        jkube.io/git-url: git@github.com:dthibau/springcloudsolutions.git
        jkube.io/scm-tag: HEAD
        jkube.io/git-commit: 9b17ea490debaddb6078683a5b11f18e0447cc3b
        jkube.io/git-branch: sck
      labels:
        app: delivery-service
        provider: jkube
        version: 0.0.8-SNAPSHOT
        group: org.dthibau
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: dthibau/delivery-service:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
